logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_manager_db
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
